shared:

  F: spiritually
  S: calorically
  T: materially
  N: cognitively

  C: fix
  A: appreciate
  R: reject
  E: tolerate

  IP: anorexic
  EP: obese
  IJ: pushy
  EJ: submissive

  CF: verbalize
  AF: understand

  CS: do housework
  AS: dine

  CT: give
  AT: take

  CN: lead
  AN: follow

