shared:

  F: social, audible, affective
  S: caloric, sensual, athletic
  T: financial, tangible, commercial
  N: cognitive, visible, intellectual

  J: strong, laborious, slow
  P: excited, fun, fast
  I: productive, hyperactive
  E: receptive, greedy

