shared:

  F: spiritually
  S: calorically
  T: materially
  N: cognitively

  IP: anorexic
  EP: obese
  IJ: pushy
  EJ: submissive

  CF: verbalize
  AF: understand

  CS: cook
  AS: ingest

  CT: build
  AT: take

  CN: plan
  AN: follow

