shared:

  F: spiritually
  S: calorically
  T: materially
  N: cognitively

  C: fix
  A: take
  R: reject
  E: tolerate

  IP: anorexic
  EP: obese
  IJ: pushy
  EJ: submissive

  CF: verbalize
  AF: understand

  CS: do housework
  AS: ingest

  CT: give
  AT: take

  CN: plan
  AN: follow

