shared:

  F: spiritual
  S: calorical
  T: material
  N: cognitive

  C: fix
  A: appreciate
  R: reject
  E: tolerate

  IP: anorexic
  EP: obese
  IJ: dominant
  EJ: submissive

  CF: tell why
  AF: believe

  CS: do housework
  AS: dine

  CT: give
  AT: take

  CN: show how
  AN: learn
