shared:

  F: spiritual, affective
  S: caloric, athletic
  T: material, commercial
  N: cognitive, intellectual

  J: laborious, slow
  P: playful, fast
  I: productive, hyperactive
  E: receptive, greedy

