shared:

  F: spiritual, affective
  S: calorical, athletic
  T: material, commercial
  N: cognitive, intellectual

  C: fix, improve, produce
  A: appreciate, take, consume
  R: reject, discard, decline
  E: tolerate, permit, allow

  IP: anorexic, skinny
  EP: obese, thick
  IJ: dominant, hyperactive
  EJ: submissive, passive

  CF: tell why, preach, use words
  AF: hear, understand, believe

  CS: go places, cook, use muscles
  AS: drink, snack, ingest

  CT: buy things, splurge, use credit
  AT: work, take, collect

  CN: show how, lead, use logic
  AN: learn, follow, remember
