shared:

  F: social, audible, affective
  S: caloric, sensual, athletic
  T: financial, tangible, commercial
  N: cognitive, visible, intellectual

  J: power, effectiveness
  P: speed, playfulness
  I: anorexia
  E: obesity

  EFP: listen to instrumental music
  FP: musical, emotional
  IFP: play musical instruments
  IFJ: write lyrics
  FJ: lyrical, meaningful
  EFJ: understand lyrics
