shared:
  Red: "#ee2126" # red
  N: "#f46f23" # vermillion
  orange: "#f8a11b" # orange
  IJ: "#fac71d" # amber
  mania: "#feef16" # yellow
  IP: "#9fc441" # chartreuse
  T: "#09a64c" # green
  EP: "#2c7d81" # aquamarine
  depression: "#3954a4" # blue
  EJ: "#554da0" # violet
  purple: "#6c469d" # purple
  F: "#ae3963" # magenta
  S: "#aa7942" # brown
