---
IFP: listen to music
INP: colorful details
ISP: obese
ITP: currency
IFJ: bedtime stories
INJ: insomnia
ISJ: eat protein
ITJ: credits
EFP: suicidal
ENP: forget
ESP: pace
ETP: pay cash
EFJ: words, words, words
ENJ: theorize
ESJ: housework
ETJ: indebted
