---
aaa: 12345678901234567890
isp: carb-load
inp: do research
ifp: listen to music
itp: get cash
esp: go places
enp: make decisions
etp: pay cash upfront
efp: prioritize
esj: do housework
enj: theorize
etj: buy on credit
efj: influence people
isj: eat protein and sit
inj: wait for results
ifj: listen to feedback
itj: earn repayments
zzz: 12345678901234567890
