---
ISP: carb-load
INP: look at colors
IFP: listen to music
ITP: earn wages
ESP: pace
ENP: make plans
ETP: pay cash
EFP: express emotions
ESJ: do housework
ENJ: theorize
ETJ: buy on credit
EFJ: verbalize
ISJ: eat protein
INJ: look at the results
ITJ: earn a salary
IFJ: listen to words
