---
IFP: music
INP: sunrise
ISP: obese
ITP: currency
IFJ: stories
INJ: wrong!
ISJ: protein
ITJ: credits
EFP: suicidal
ENP: guess
ESP: pace
ETP: pay cash
EFJ: verbalize
ENJ: theorize
ESJ: clean
ETJ: indebted
