---
ITP: earn currency
ITJ: collect credits
ISP: binge
ISJ: eat protein
INP: look at colors
INJ: look at results
IFP: listen to music
IFJ: listen to words
ETP: pay cash
ETJ: use credit
ESP: pace
ESJ: do housework
ENP: visualize
ENJ: theorize
EFP: emote
EFJ: verbalize
