---
IFP: listen to music
INP: colorful details
ISP: obese
ITP: wages
IFJ: bedtime stories
INJ: insomniac
ISJ: eat protein
ITJ: return on investment
EFP: suicidal
ENP: forget
ESP: pace
ETP: pay cash
EFJ: words, words, words
ENJ: theorize
ESJ: housework
ETJ: indebted
