---
aaa: 12345678901234567890
isp: carb-load
inp: look at colors
ifp: listen to music
itp: earn wages
esp: walk
enp: make plans
etp: pay cash
efp: express emotions
esj: do housework
enj: theorize
etj: buy on credit
efj: verbalize
isj: eat protein
inj: look at the results
itj: earn a salary
ifj: listen to words
zzz: 12345678901234567890
