---
IFP: listen to music
INP: colorful details
ISP: binge on carbs
ITP: wages
IFJ: bedtime stories
INJ: insomniac
ISJ: eat protein
ITJ: collect returns
EFP: suicidal
ENP: guess
ESP: pace
ETP: pay cash
EFJ: words, words, words
ENJ: theorize
ESJ: housework
ETJ: indebted
