---
isp: eat carbs
esp: walk or run
esj: do housework
isj: eat protein and sit
inp: look at pictures
enp: make decisions
enj: theorize
inj: look at results
itp: earn cash
etp: spend cash
etj: buy on credit
itj: earn repayments
ifp: listen to music
efp: express emotions
efj: use words
ifj: listen to stories

