---
isp: eat desert and go
esp: get up and walk
esj: do housework
isj: sit and eat protein
inp: look at colors
enp: make decisions
enj: theorize
inj: watch for results
itp: earn cash
etp: spend cash
etj: buy on credit
itj: earn repayments
ifp: listen to music
efp: express emotions
efj: use words
ifj: listen for meaning

