F: spiritual
S: physical
T: material
N: mental

J: strength
P: energy
I: mania
E: depression

EP: get energy
IP: burn energy
IJ: use strength
EJ: recover strength

FP: expressive
NP: inductive
SP: herbivorous
TP: labor

FJ: lexical
NJ: deductive
SJ: carnivorous
TJ: capital

EFP: listen to intonation
IFP: express emotions
IFJ: use words
EFJ: understand meaning

ESP: eat carbs
ISP: walk
ISJ: use muscles
ESJ: digest protein

ENP: see colorful specifics
INP: generalize
INJ: use logic
ENJ: analyze results

ETP: collect wages
ITP: pay cash
ITJ: use credit
ETJ: invest income

F-alt: social, audible, affective
S-alt: caloric, sensual, athletic
T-alt: financial, tangible, commercial
N-alt: cognitive, visible, intellectual

J-alt: power, effectiveness
P-alt: speed, playfulness
I-alt: anorexia
E-alt: obesity

EFP-alt: listen to instrumental music
FP-alt: musical, emotional
IFP-alt: sing, play musical instruments
IFJ-alt: preach, write lyrics
FJ-alt: lyrical, meaningful
EFJ-alt: understand lyrics

ESP-alt: carb load, eat sweets
SP-alt: fast, prey
ISP-alt: jog, play sports
ISJ-alt: lift weights, do chores
SJ-alt: strong, predator
ESJ-alt: drink protein shakes, eat protein bars
