P: get energy
I: burn energy
J: use strength
E: recover strength

P-alt: accept, absorb, appreciate resources
I-alt: flee, practice, excercise, play games
J-alt: fight, work, labor, achieve goals
E-alt: take, consume, process resources

F: people
S: places
T: things
N: ideas

F-alt: friends, enemies, family, neighbors, colleagues, employers, employees, 
S-alt: homes, gardens, farms, parks, rivers, mountains, trails
T-alt: tools, machines, clothing, toys, computers, furniture, cars
N-alt: theories, plans, rules, laws, programs, ideologies, concepts

FP: listen to intonation
FP-alt: listen to music
IF: express emotions
IF-alt: talk, sing, play musical instruments
FJ: influence
FJ-alt: preach, write lyrics
EF: understand meaning
EF-alt: understand lyrics

SP: eat carbs
SP-alt: carb load, eat sweets
IS: run
IS-alt: run away, leave
SJ: clean 
SJ-alt: cultivate
ES: lie down
ES-alt: drink protein shakes, eat protein bars, eat protein after

NP: see colorful specifics
NP-alt: watch the sunrise, learn facts
IN: generalize
IN-alt: intuit, guess
NJ: improve
NJ-alt: theorize, prove, use logic
EN: analyze results
EN-alt: watch endings, learn consequences

TP: earn wages
TP-alt: compete for prizes
IT: spend cash
IT-alt: buy outright, pay cash upfront
TJ: invest in
TJ-alt: pay over time
ET: earn repayments
ET-alt: earn a salary
