P: get energy
I: burn energy
J: use strength
E: recover strength

P-alt: accept, absorb, appreciate resources
I-alt: flee, practice, excercise, play games
J-alt: fight, work, labor, achieve goals
E-alt: take, consume, process resources

F: people
S: places
T: things
N: ideas

F-alt: spiritual, political, religious, musical, social, audible, affective
S-alt: physical, agrarian, caloric, sensual, athletic
T-alt: financial, material, tangible, commercial
N-alt: mental, cognitive, visible, intellectual

EP: get energy
IP: burn energy
IJ: use strength
EJ: recover strength

FP: listen to music
FP-alt: listen to intonation
IF: express emotions
IF-alt: sing, play musical instruments
FJ: use words
FJ-alt: preach, write lyrics
EF: understand meaning
EF-alt: understand lyrics

SP: eat carbs
SP-alt: carb load, eat sweets
IS: walk
IS-alt: run, play sports
SJ: use muscles
SJ-alt: lift weights, do chores
ES: lie down
ES-alt: drink protein shakes, eat protein bars, eat protein after

NP: see colorful specifics
NP-alt: watch the sunrise, learn facts
IN: generalize
IN-alt: intuit, guess
NJ: close your eyes
NJ-alt: theorize, prove, use logic
EN: analyze results
EN-alt: watch endings, learn consequences

TP: earn wages
TP-alt: compete for prizes
IT: pay cash upfront
IT-alt: buy outright
TJ: use credit
TJ-alt: pay over time
ET: earn repayments
ET-alt: earn a salary
