shared:
  I:
    - manic
    - up, on, high, hot, fast
    - young, liberal, stimulated, energetic, labile
    - stressed, irritable, anxious, hypervigilant, restless
    - wired, overexcited, chaotic, overactive, oversensitive
    - productive, alert, active, fast, powerful
    - fight & flight
    - sympathetic nervous system
  IP:
    - rejecting
    - not accepting the things you should accept
    - irritable mania
  IJ:
    - splurging
    - changing the things you should not change
    - euphoric mania

  E:
    - depressed
    - down, off, low, cold, slow
    - old, conservative, sedated, calm, stable
    - bored, unresponsive, listless, oblivious, lethargic
    - tired, fatigued, worn out, underactive, insensitive
    - receptive, tolerant, passive, slow, appreciative
    - rest & digest; feed & breed
    - parasympathetic nervous system
  EP:
    - binging
    - accepting the things you should not accept
    - agitated depression
  EJ:
    - lazing
    - not changing the things you should change
    - lethargic depression

  F:
    - people
    - spiritual, affective, social, emotional, interpersonal
    - souls, values, hope
    - suicidal or homicidal
    - communication & conversation
    - religion & politics
    - stories & morals
    - meaning & intonation
  FP:
    - listen
    - hear, understand, and believe
    - music & lyrics
    - sounds
    - auditory
    - audience
  FJ:
    - talk
    - tell people
    - sing or preach
    - read & write
    - laugh & cry, scream & shout
    - verbal

  S:
    - places
    - physical, caloric, spatial, athletic, sensual
    - body, food, drugs
    - anorexic or obese
    - travel & exploration
    - food & medicine
    - hunting, farming & gardening
    - cooking & cleaning
  SP:
    - eat
    - smells & tastes
    - olfactory
    - chew, swallow, and digest
    - meals
  SJ:
    - do things
    - go places
    - actions & movements
    - walk, run & exercise
    - hit & lift weights

  N:
    - ideas
    - mental, cognitive, abstract, theoretical, intangible
    - mind, knowledge, memories
    - ignorant or trivial
    - science & philosophy
    - research & design & software
    - art & drawing
    - knowledge
    - creative
    - conceivable
    - visual


  NP:
    - watch
    - research, analyze, and memorize
    - color & movement
    - sights
    - patterns & exceptions
  NJ:
    - think
    - visualize & predict
    - plan
    - imagine, dream & theorize

  T:
    - things
    - material, financial, commercial, measurable, tangible
    - hands, posessions & crafts
    - destitute or miserly
    - tools & machines & hardware
    - weapons & shelter & clothes & textiles
    - taxes
  TP:
    - earn
    - sell
    - compete
    - tactile
    - win
    - collect
    - wages
  TJ:
    - spend
    - buy
    - pay
    - invest
    - use credit

  P:
    - get energy
    - accept things
    - take, receive & consume
    - appreciate, enjoy & internalize
    - sense, perceive, and take
    - collect & hoard
    - dependent
  J:
    - use energy
    - change things
    - give, output & produce
    - destroy, rebuild, fix & improve
    - demonstrate, provide & externalize
    - discard & waste
    - parental

