shared:
  F:
    - affective
    - emotional
    - personal
    - spiritual
    - moral
    - musical
    - auditory
  S:
    - physical
    - spatial
    - environmental
    - sensual
    - active
    - athletic
    - olfactory
  T:
    - financial
    - tangible
    - material
    - fiscal
    - transferable
    - commercial
    - tactile
  N:
    - mental
    - symbolic
    - abstract
    - cognitive
    - scientific
    - artistic
    - visual

  P:
    - get energy
    - accept things
    - consume resources
    - rest & digest
  J:
    - use strength
    - change things
    - produce resources
    - fight & flee

  I:
    - deficit
    - low reserves
    - mania
    - introversion
  E:
    - surplus
    - high reserves
    - depression
    - extroversion


  FP:
    - listen to music
    - hear intonation
    - accept emotions
  FJ:
    - influence people
    - write stories
    - give sermons
  SP:
    - eat carbs
    - eat sweets
    - eat dessert
  SJ:
    - do housework
    - hunt or gather
    - lift weights
  TP:
    - earn wages
    - collect cash
    - compete for prizes
  TJ:
    - use credit
    - buy now & pay later
    - increase debt
  NP:
    - watch videos
    - look at colors
    - see movement
  NJ:
    - theorize
    - make plans
    - predict consequences
    - create procedures


  IF:
    - suicidal
    - humble
    - modest
  EF:
    - homicidal
    - egotistical
    - arrogant
  IS:
    - anorexic
    - underweight
    - skinny
  ES:
    - obese
    - overweight
    - fat
  IT:
    - bankrupt
    - poor
    - homeless
  ET:
    - filthy rich
    - affluent
    - landed

  IN:
    - ignorant
    - forgetful
    - clueless
  EN:
    - overeducated
    - pedantic
    - trivial


