---
IFP: tone of voice
INP: lights, color, action
ISP: breakfast cereals
ITP: goods & services
IFJ: stories
INJ: shapes & shadows
ISJ: main course
ITJ: regular investments
EFP: apologize
ENP: ignore
ESP: run away
ETP: pay cash
EFJ: tell why
ENJ: show how
ESJ: clean & farm
ETJ: use credit
