shared:

  F: emotionally
  S: physically
  T: financially
  N: mentally

  ¬↓: thin
  ↓: fat
  ↑: strong
  ¬↑: weak

  F↑: verbalize
  F¬↑: remain silent
  F↓: listen
  F¬↓: tune out

  S↑: do housework
  S¬↑: sit down
  S↓: eat
  S¬↓: fast

  T↑: buy on credit
  T¬↑: save
  T↓: collect income
  T¬↓: stop working

  N↑: think
  N¬↑: stop worrying
  N↓: watch & learn
  N¬↓: close your eyes

