shared:
  I:
    - mania
    - introversion
    - stressed

  E:
    - depression
    - extroversion
    - bored

  F:
    - affective
    - spiritual
    - musical
    - interpersonal
    - emotional
  IF:
    - suicidal
    - humble
    - submissive
    - modest
  EF:
    - homicidal
    - egotistical
    - dominant
    - arrogant
  FP:
    - listen
    - hear
    - understand
    - believe
  FJ:
    - talk
    - tell people
    - sing or preach
    - read or write

  S:
    - physical
    - caloric
    - athletic
    - spatial
    - sensual

  IS:
    - losing weight
    - anorexic
    - skinny
    - thin
  ES:
    - gaining weight
    - obese
    - fat
    - soft
  SP:
    - eat
    - chew
    - swallow
    - digest
  SJ:
    - do
    - go places
    - walk or exercise
    - cook or clean

  T:
    - financial
    - material
    - commercial
    - fiscal
    - taxable

  IT:
    - wasting money
    - homeless
    - bankrupt
    - poor
  ET:
    - hoarding money
    - miserly
    - loaded
    - filthy rich
  TP:
    - earn
    - sell
    - compete
    - collect
  TJ:
    - spend
    - buy things
    - use cash or credit
    - pay or invest

  N:
    - mental
    - cognitive
    - artistic
    - scientific
    - reasonable
  IN:
    - forgetful
    - ignorant
    - clueless
    - unrealistic
  EN:
    - stupid
    - trivial
    - know-it-all
    - pedantic
  NP:
    - watch
    - learn
    - analyze
    - memorize
  NJ:
    - visualize
    - think of ideas
    - plan or predict
    - imagine or dream


  P:
    - intake
    - get energy
    - accept things
    - take
    - consume
    - internalize
  J:
    - output
    - use energy
    - change things
    - give
    - produce
    - externalize

