---
IFP: intonation
INP: lights, color, action
ISP: simple carbs
ITP: goods & services
IFJ: meaning
INJ: shapes & patterns
ISJ: protein
ITJ: regular income
EFP: express emotions
ENP: synthesize facts
ESP: run
ETP: pay cash
EFJ: use language
ENJ: use logic
ESJ: use muscle
ETJ: use credit
