---
IFP: inspirational music
INP: facts & figures
ISP: breakfast cereals
ITP: goods & services
IFJ: bedtime stories
INJ: cause & effect
ISJ: dinner meats
ITJ: regular investments
EFP: sing
ENP: tactics
ESP: play outside
ETP: pay cash
EFJ: preach
ENJ: strategy
ESJ: do chores
ETJ: use credit
