---
ITP: earn wages to store cash
ITJ: earn a salary to build credit
ISP: eat carbs to store glycogen
ISJ: eat protein to build muscles
INP: look at specifics to store facts
INJ: look at patterns to build logic
IFP: listen to intonation to store emotions
IFJ: listen to words to build language
ETP: use cash to buy outright
ETJ: use loans to buy on credit
ESP: use glycogen to move
ESJ: use muscles to lift or hit
ENP: use facts to decide on tactics
ENJ: use logic to create a strategy
EFP: use emotions to talk
EFJ: use language to write
