shared:

  F: spiritual
  S: physical
  T: material
  N: mental

  J: strength
  P: energy
  I: mania
  E: depression

  IF: communicate
  IS: move
  IT: purchase
  IN: think

  EF: listen & understand
  ES: eat & digest
  ET: earn & collect
  EN: learn & analyze

  EP: get energy
  IP: burn energy
  IJ: use strength
  EJ: recover strength

  FP: emotional
  NP: imaginative
  SP: fast
  TP: labor

  FJ: moral
  NJ: logical
  SJ: powerful
  TJ: capital

  EFP: listen to music
  IFP: express emotions
  IFJ: use words
  EFJ: understand meaning

  ESP: eat carbs
  ISP: walk or run
  ISJ: use muscles
  ESJ: digest protein

  ENP: see causes
  INP: know or guess
  INJ: use logic
  ENJ: analyze results

  ETP: earn wages
  ITP: pay cash
  ITJ: use credit
  ETJ: collect income
