shared:

  F: spiritual
  S: physical
  T: material
  N: mental

  J: strength
  P: energy
  I: mania
  E: depression

  EP: get energy
  IP: burn energy
  IJ: use strength
  EJ: recover strength

  FP: expressive
  NP: inductive
  SP: herbivorous
  TP: labor

  FJ: lexical
  NJ: deductive
  SJ: carnivorous
  TJ: capital

  EFP: listen to intonation
  IFP: emote
  IFJ: use words
  EFJ: understand meaning

  ESP: eat carbs
  ISP: run
  ISJ: use muscles
  ESJ: digest protein

  ENP: see specifics
  INP: generalize
  INJ: use logic
  ENJ: believe results

  ETP: collect wages
  ITP: pay cash
  ITJ: use credit
  ETJ: invest income
