shared:

  F: emotionally
  S: physically
  T: financially
  N: mentally

  IP: thin
  EP: fat
  IJ: strong
  EJ: weak

  FC: talk
  FT: be quiet
  FA: listen
  FR: tune out

  SC: move
  ST: sit still
  SA: eat
  SR: fast

  TC: buy on credit
  TT: save your money
  TA: work
  TR: quit

  NC: think
  NT: stop worrying
  NA: watch
  NR: close your eyes

