shared:

  F: emotionally
  S: physically
  T: financially
  N: mentally

  IP: thin
  EP: fat
  IJ: strong
  EJ: weak

  CF: talk
  AF: listen

  CS: labor
  AS: eat

  CT: spend
  AT: earn

  CN: think
  AN: watch

