shared:
  I:
    - mania
    - insomnia
    - overactivity
    - stress
    - over-stimulation

  E:
    - depression
    - hypersomnia
    - underactivity
    - boredom
    - under-stimulation

  F:
    - spiritual
    - social
    - political
    - religious
    - verbal
  S:
    - physical
    - sensual
    - athletic
    - spatial
    - mobile
  T:
    - material
    - tangible
    - commercial
    - financial
    - transferable
  N:
    - mental
    - intangible
    - intellectual
    - cognitive
    - conceptual


  P:
    - acute
    - intermittent
    - bursty
  J:
    - chronic
    - constant
    - steady


  IFP:
    - talk
    - emote
    - sing
  IFJ:
    - write
    - use words
    - preach
  EFP:
    - listen to music
    - understand intonation
    - hear harmonies
  EFJ:
    - listen to words
    - understand meaning
    - hear rhythms

  ISP:
    - walk
    - do aerobics
    - play sports
  ISJ:
    - do chores
    - use muscles
    - lift weights

  ESP:
    - eat breakfast
    - digest carbs
    - taste sweets
  ESJ:
    - eat dinner
    - digest protein
    - taste savories

  ITP:
    - pay cash
    - buy outright
    - spend money
  ITJ:
    - use credit
    - buy over time
    - borrow money
  ETP:
    - earn wages
    - collect tips
    - win lump sums
  ETJ:
    - earn investment income
    - collect retirement income
    - win annuities

  INP:
    - guess
    - imagine
    - intuit
  INJ:
    - use logic
    - prove
    - reason
  ENP:
    - watch beginnings
    - learn specific facts
    - look at causes
    - see the sun rise
  ENJ:
    - watch endings
    - learn general rules
    - look at effects
    - see the sun set

