shared:

  F: emotionally
  S: physically
  T: financially
  N: mentally

  C: change
  A: accept
  R: refuse
  E: endure

  IP: thin
  EP: fat
  IJ: strong
  EJ: weak

  CF: talk
  AF: listen

  CS: cook
  AS: eat

  CT: spend
  AT: earn

  CN: lead
  AN: follow
