shared:

  F: spiritually
  S: physically
  T: materially
  N: mentally

  ¬↓: thin
  ↓: fat
  ↑: strong
  ¬↑: weak

  F↑: talk
  F¬↑: be quiet
  F↓: listen
  F¬↓: tune out

  S↑: walk
  S¬↑: sit down
  S↓: eat
  S¬↓: fast

  T↑: buy on credit
  T¬↑: save
  T↓: collect income
  T¬↓: stop working

  N↑: think
  N¬↑: stop worrying
  N↓: watch
  N¬↓: close your eyes

