shared:
  I:
    - mania
    - introversion


  E:
    - depression
    - extroversion


  F:
    - affective
    - spiritual
    - musical
    - interpersonal
    - emotional
    - auditory
  IF:
    - suicidal
    - humble
    - modest
  EF:
    - homicidal
    - egotistical
    - arrogant
  FP:
    - listen to music
    - hear intonation
    - accept emotions
  FJ:
    - influence people
    - write stories
    - give sermons

  S:
    - physical
    - caloric
    - athletic
    - spatial
    - sensual
    - olfactory

  IS:
    - anorexic
    - underweight
    - skinny
  ES:
    - obese
    - overweight
    - fat
  SP:
    - eat carbs
    - eat sweets
    - eat dessert
  SJ:
    - do housework
    - hunt or gather
    - lift weights

  T:
    - financial
    - material
    - commercial
    - fiscal
    - tangible
    - tactile

  IT:
    - bankrupt
    - poor
    - homeless
  ET:
    - filthy rich
    - affluent
    - landed
  TP:
    - earn wages
    - collect cash
    - compete for prizes
  TJ:
    - use credit
    - buy now & pay later
    - increase debt

  N:
    - mental
    - cognitive
    - artistic
    - scientific
    - abstract
    - visual
  IN:
    - ignorant
    - forgetful
    - clueless
  EN:
    - overeducated
    - pedantic
    - trivial
  NP:
    - watch videos
    - look at colors
    - see movement
  NJ:
    - theorize
    - make plans
    - predict consequences


  P:
    - get energy
    - accept things
    - consume resources
  J:
    - use strength
    - change things
    - produce resources

