shared:

  F: emotionally
  S: physically
  T: financially
  N: mentally

  IP: thin
  EP: fat
  IJ: strong
  EJ: weak

  FC: talk
  FA: listen

  SC: move
  SA: eat

  TC: spend
  TA: earn

  NC: think
  NA: watch

